name: push_nuget

# on push on master
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    env:
      VERSION: 1.1.$GITHUB_RUN_NUMBER 
    steps:
    - name: Git Checkout
      uses: actions/checkout@master

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      
    - name: Nuget Pack
      run: nuget pack ./deployment/VL.Skia3d.nuspec -Version $VERSION
      
    - name: Nuget Push
      run: nuget push *.nupkg ${{secrets.NUGET_KEY}} -src https://api.nuget.org/v3/index.json
